# ANSI colors for fg:NUMBER
# https://i.stack.imgur.com/KTSQa.png

# Don't print a new line at the start of the prompt
add_newline = false

format = """
$time\
$ruby\
$nodejs\
$directory\
$git_branch\
$git_state\
$git_status\
\\$ """

[time]
disabled = true
format = "[$time]($style) "
style = "#888888"
use_12hr = true

[ruby]
disabled = true
format = "[($version )]($style)"
style = "fg:218" # pink

[directory]
# Show 1 parent directory (setting to 0 means no truncation)
truncation_length = 2
# A lovely grayish-purple
style = "fg:146"
format = "[$path]($style) "
# When in a Git repo, keep showing parent directories
truncate_to_repo = false

[git_branch]
format = "[($branch )]($style)"
style = "fg:031" # dark blue

[git_state]
cherry_pick = "[ðŸ’ PICKING](bold fg:197)" # red

[git_status]
format = """
($conflicted\
$stashed\
$deleted\
$renamed\
$modified\
$staged\
$untracked )\
($ahead_behind )""" # purple
stashed = "[stash](bold fg:222)" # yellow
staged = "[S](bold fg:222)" # yellow
conflicted = "[=](bold fg:197)" # red
untracked = "[?](bold fg:159)" # cyan
modified = "[!](bold fg:222)" # yellow
deleted = "[âœ˜](bold fg:197)" # red
behind = "[â†“](bold fg:159)" # cyan
ahead = "[â†‘](bold fg:159)" # cyan
diverged = "[â‡”](bold fg:197)" # red

[nodejs]
disabled = true
# Don't show "v3", just "3"
version_format = "${raw}"
detect_files = ["package.json", ".node-version", "yarn.lock"]
detect_folders = ["node_modules"]
# Unlike the standard nodejs module, it intentionally does not check for
# *.js or *.ts since that triggers too often
detect_extensions = []
format = "[($version )]($style)"
style = "fg:031" # dark blue

# [custom.git_worktree]
# description = "Displays git worktree directory name"
# command = "sh -c 'git_dir=$(git rev-parse --git-dir 2>/dev/null) && if echo \"$git_dir\" | grep -q \"/worktrees/\"; then top=$(git rev-parse --show-toplevel 2>/dev/null) && basename \"$top\" 2>/dev/null | tr -d \"\\n\"; fi'"
# when = "sh -c 'git rev-parse --is-inside-work-tree >/dev/null 2>&1 && git rev-parse --git-dir 2>/dev/null | grep -q \"/worktrees/\"'"
# format = "[worktree: $output]($style)\n"
# style = "fg:245"                                                                                                                                                                                                                 # subtle gray
